In [1]:
import pandas as pd
import numpy as np
import yfinance as yf

In [2]:
ticker = 'OSK'
df = yf.download(ticker, period="max", interval="1d", auto_adjust=False)
df.head()

[*********************100%***********************]  1 of 1 completed

Price      Adj Close     Close      High       Low      Open   Volume
Ticker           OSK       OSK       OSK       OSK       OSK      OSK
Date
1985-10-02  1.359799  2.791667  2.833333  2.791667  2.791667  4849200
1985-10-03  1.380093  2.833333  2.875000  2.833333  2.833333  1974000
1985-10-04  1.380093  2.833333  2.875000  2.833333  2.833333   694800
1985-10-07  1.359799  2.791667  2.833333  2.791667  2.833333   337200
1985-10-08  1.359799  2.791667  2.833333  2.791667  2.791667   436200

In [4]:
df.columns = ['Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume']
df.head()

            Adj Close     Close      High       Low      Open   Volume
Date
1985-10-02   1.359799  2.791667  2.833333  2.791667  2.791667  4849200
1985-10-03   1.380093  2.833333  2.875000  2.833333  2.833333  1974000
1985-10-04   1.380093  2.833333  2.875000  2.833333  2.833333   694800
1985-10-07   1.359799  2.791667  2.833333  2.791667  2.833333   337200
1985-10-08   1.359799  2.791667  2.833333  2.791667  2.791667   436200

In [2]:
# list of assets currently in portfolio
portfolio_assets = [
    'ACM',
    'OSK',
    'PATH',
    'RGLD',
    'AAAU',
    'CIBR',
    'IBIT',
    'ITA',
    'SGDM',
    'USO',
    'USXF',
    'XHE'
]

# iterate to get the data
for ticker in portfolio_assets:
    try:
        df_tmp = yf.download(ticker, period="max", interval="1d", auto_adjust=False)
        df_tmp.columns = ['Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume']
        # save the data as a parquet file
        df_tmp.to_parquet(f'data/{ticker}.parquet')
    except Exception as e:
        print(f"Could not load ticker:\t{ticker}\n{e}")

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [7]:
!pip install pyarrow fastparquet

Collecting pyarrow
  Using cached pyarrow-22.0.0-cp311-cp311-macosx_12_0_arm64.whl (34.3 MB)
Collecting fastparquet
  Using cached fastparquet-2024.11.0-cp311-cp311-macosx_11_0_arm64.whl (683 kB)
Requirement already satisfied: pandas>=1.5.0 in /Users/terrilltoe/.pyenv/versions/3.11.4/envs/mrs/lib/python3.11/site-packages (from fastparquet) (2.3.3)
Requirement already satisfied: numpy in /Users/terrilltoe/.pyenv/versions/3.11.4/envs/mrs/lib/python3.11/site-packages (from fastparquet) (2.3.5)
Collecting cramjam>=2.3 (from fastparquet)
  Using cached cramjam-2.11.0-cp311-cp311-macosx_11_0_arm64.whl (1.7 MB)
Collecting fsspec (from fastparquet)
  Downloading fsspec-2025.12.0-py3-none-any.whl (201 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 201.4/201.4 kB 4.9 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: packaging in /Users/terrilltoe/.pyenv/versions/3.11.4/envs/mrs/lib/python3.11/site-packages (from fastparquet) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/terrilltoe/.pyenv/versions/3.11.4/envs/mrs/lib/python3.11/site-packages (from pandas>=1.5.0->fastparquet) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/terrilltoe/.pyenv/versions/3.11.4/envs/mrs/lib/python3.11/site-packages (from pandas>=1.5.0->fastparquet) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/terrilltoe/.pyenv/versions/3.11.4/envs/mrs/lib/python3.11/site-packages (from pandas>=1.5.0->fastparquet) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/terrilltoe/.pyenv/versions/3.11.4/envs/mrs/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.17.0)
Installing collected packages: pyarrow, fsspec, cramjam, fastparquet
Successfully installed cramjam-2.11.0 fastparquet-2024.11.0 fsspec-2025.12.0 pyarrow-22.0.0

[notice] A new release of pip is available: 23.1.2 -> 25.3
[notice] To update, run: pip install --upgrade pip